---

- hosts: all
  become: true
  pre_tasks: 

  - name: Install Updates (CentOS)
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks: 

  - name: Install Apache and PHP (Ubuntu)
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:
  
  - name: Install PostgreSQL (CentOS)
    dnf:
      name: postgresql-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package: 
      name: samba
      state: latest