---

- hosts: all
  become: true
  tasks: 

  - name: uninstall apache2 package
    apt: 
      name: apache2
      state: absent
    when: ansible_distribution in ["Debian","Ubuntu"]


  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Debian","Ubuntu"]
